[install]
is_configured = 1

[ui]
is_visible = true
label = Windows Detection Lab

[launcher]
author = Ravi Teja
description = Windows SIEM Detection Engineering Lab using Splunk Enterprise, Windows Security Logs and Sysmon
version = 1.0.0

[package]
id = windows_detection_lab
check_for_updates = false
